version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password 
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/demo/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/demo/certs/localhostkey.pem
    ports:
      - 8890:8080
      - "8843:8443"
    depends_on:
      postgres_keycloak_demo:
        condition: service_healthy
    networks:
      - keycloak_demo_dev_network
    volumes:
      - ./certs:/opt/keycloak/demo/certs

  postgres_keycloak_demo:
    image: "postgres:14.2"
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_demo:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_demo_dev_network

volumes:
  pgdata_keycloak_demo: 
networks:
  keycloak_demo_dev_network:
    driver: bridge


